/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/opening-balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOpeningBalances"];
        put: operations["replaceOpeningBalances"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:unpost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unpost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:restore-deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreDeleted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}:approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}/revisions/{revision}:restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/periods/{periodId}:reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopenPeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/periods/{periodId}:close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closePeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/opening-balances:import-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importOpeningBalances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/opening-balances:confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmOpeningBalances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/finance-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/documents/{documentId}:extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extractMock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/documents/{documentId}:create-voucher-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createVoucherDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/dimension-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDimensionTypes"];
        put?: never;
        post: operations["createDimensionType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/dimension-types/{typeId}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDimensionValues"];
        put?: never;
        post: operations["createDimensionValue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch: operations["updateMember"];
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/vouchers/{voucherId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["revisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/reports/sub-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/reports/income-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incomeStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/reports/general-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["generalLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/reports/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balanceSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPeriods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/member-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findMemberCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/documents/{documentId}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["extractions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/documents/{documentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledgers/{ledgerId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Line: {
            /** Format: uuid */
            accountId: string;
            side: string;
            currency: string;
            originalAmount: number;
            exchangeRate: number;
            summary?: string;
        };
        Update: {
            /** Format: int64 */
            expectedVersion: number;
            /** Format: uuid */
            periodId: string;
            /** Format: date */
            voucherDate: string;
            voucherType: string;
            voucherNumber: string;
            summary?: string;
            lines: components["schemas"]["Line"][];
        };
        Voucher: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            /** Format: uuid */
            periodId?: string;
            /** Format: date */
            voucherDate?: string;
            voucherType?: string;
            voucherNumber?: string;
            summary?: string;
            status?: string;
            approvalRequired?: boolean;
            /** Format: int64 */
            version?: number;
            lines?: components["schemas"]["Line"][];
        };
        OpeningBalanceLine: {
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            periodId: string;
            currency: string;
            dimensionKey?: string;
            debitOriginal: number;
            creditOriginal: number;
            exchangeRate: number;
        };
        OpeningBalances: {
            lines: components["schemas"]["OpeningBalanceLine"][];
        };
        OpeningBalance: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            /** Format: uuid */
            periodId?: string;
            /** Format: uuid */
            accountId?: string;
            currency?: string;
            dimensionKey?: string;
            debitOriginal?: number;
            creditOriginal?: number;
            exchangeRate?: number;
            debitBase?: number;
            creditBase?: number;
            confirmed?: boolean;
        };
        Create: {
            name: string;
            accountingStandardCode: string;
            accountingStandardVersion: string;
            baseCurrency: string;
            /** Format: date */
            startDate: string;
            approvalEnabled?: boolean;
        };
        Ledger: {
            /** Format: uuid */
            id?: string;
            name?: string;
            accountingStandardCode?: string;
            accountingStandardVersion?: string;
            baseCurrency?: string;
            /** Format: date */
            startDate?: string;
            approvalEnabled?: boolean;
            status?: string;
        };
        Reason: {
            reason: string;
        };
        Comment: {
            comment: string;
        };
        PeriodAction: {
            reason: string;
        };
        Period: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            periodCode?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
        };
        AddMember: {
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            role: "OWNER" | "EDITOR" | "REVIEWER" | "VIEWER" | "AGENT";
        };
        Member: {
            /** Format: uuid */
            userId?: string;
            /** @enum {string} */
            role?: "OWNER" | "EDITOR" | "REVIEWER" | "VIEWER" | "AGENT";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            displayName?: string;
            email?: string;
        };
        Filters: {
            accountCodes?: string[];
            currency?: string;
        };
        Query: {
            metric: string;
            periodFrom?: string;
            periodTo?: string;
            groupBy: string[];
            filters?: components["schemas"]["Filters"];
        };
        FinanceQueryLine: {
            groupKey?: string;
            amount?: number;
        };
        Document: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            objectKey?: string;
            fileName?: string;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            sha256?: string;
            status?: string;
            duplicateWarning?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        Extraction: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            documentId?: string;
            provider?: string;
            status?: string;
            structuredResult?: string;
        };
        DimensionTypeCreate: {
            code: string;
            name: string;
            required?: boolean;
        };
        DimensionType: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            code?: string;
            name?: string;
            required?: boolean;
            status?: string;
        };
        DimensionValueCreate: {
            code: string;
            name: string;
        };
        DimensionValue: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            /** Format: uuid */
            dimensionTypeId?: string;
            code?: string;
            name?: string;
            status?: string;
        };
        UpdateMember: {
            /** @enum {string} */
            role: "OWNER" | "EDITOR" | "REVIEWER" | "VIEWER" | "AGENT";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            issuer?: string;
            subject?: string;
            displayName?: string;
            email?: string;
            status?: string;
        };
        Revision: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            revision?: number;
            action?: string;
            /** Format: uuid */
            actorId?: string;
            reason?: string;
            beforeData?: string;
            afterData?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        TrialBalanceLine: {
            /** Format: uuid */
            accountId?: string;
            code?: string;
            name?: string;
            category?: string;
            debit?: number;
            credit?: number;
            balance?: number;
        };
        LedgerLine: {
            /** Format: uuid */
            voucherId?: string;
            voucherNumber?: string;
            /** Format: date */
            voucherDate?: string;
            accountCode?: string;
            accountName?: string;
            side?: string;
            amount?: number;
            dimensionKey?: string;
        };
        Statement: {
            /** Format: int32 */
            totalLines?: number;
            lines?: components["schemas"]["StatementLine"][];
        };
        StatementLine: {
            code?: string;
            name?: string;
            amount?: number;
        };
        Job: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            jobType?: string;
            /** Format: uuid */
            aggregateId?: string;
            status?: string;
            /** Format: int32 */
            attempts?: number;
            /** Format: date-time */
            nextRunAt?: string;
            lockedBy?: string;
        };
        Entry: {
            /** Format: uuid */
            id?: string;
            aggregateType?: string;
            /** Format: uuid */
            aggregateId?: string;
            /** Format: int32 */
            revision?: number;
            action?: string;
            /** Format: uuid */
            actorId?: string;
            reason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        Account: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ledgerId?: string;
            code?: string;
            name?: string;
            category?: string;
            normalBalance?: string;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Update"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOpeningBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpeningBalance"][];
                };
            };
        };
    };
    replaceOpeningBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpeningBalances"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpeningBalance"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ledger"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ledger"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    unpost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    reverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    restoreDeleted: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Comment"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Comment"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    restoreRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    reopenPeriod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                periodId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeriodAction"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Period"];
                };
            };
        };
    };
    closePeriod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                periodId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeriodAction"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Period"];
                };
            };
        };
    };
    importOpeningBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OpeningBalance"][];
                };
            };
        };
    };
    confirmOpeningBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Member"][];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMember"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Member"];
                };
            };
        };
    };
    query: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Query"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FinanceQueryLine"][];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Document"][];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Document"];
                };
            };
        };
    };
    extractMock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Extraction"];
                };
            };
        };
    };
    createVoucherDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Voucher"];
                };
            };
        };
    };
    listDimensionTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DimensionType"][];
                };
            };
        };
    };
    createDimensionType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DimensionTypeCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DimensionType"];
                };
            };
        };
    };
    listDimensionValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DimensionValue"][];
                };
            };
        };
    };
    createDimensionValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                typeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DimensionValueCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DimensionValue"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMember"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Member"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ledger"];
                };
            };
        };
    };
    revisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                voucherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Revision"][];
                };
            };
        };
    };
    trialBalance: {
        parameters: {
            query?: {
                periodCode?: string;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrialBalanceLine"][];
                };
            };
        };
    };
    subLedger: {
        parameters: {
            query?: {
                periodCode?: string;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerLine"][];
                };
            };
        };
    };
    incomeStatement: {
        parameters: {
            query?: {
                periodCode?: string;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Statement"];
                };
            };
        };
    };
    generalLedger: {
        parameters: {
            query?: {
                periodCode?: string;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerLine"][];
                };
            };
        };
    };
    balanceSheet: {
        parameters: {
            query?: {
                periodCode?: string;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Statement"];
                };
            };
        };
    };
    listPeriods: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Period"][];
                };
            };
        };
    };
    findMemberCandidates: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Job"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Document"];
                };
            };
        };
    };
    extractions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Extraction"][];
                };
            };
        };
    };
    content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Entry"][];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ledgerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Account"][];
                };
            };
        };
    };
}
