import { App as AntApp, Alert, Button, Card, Form, Input, Select, Space, Table, Tabs, Tag, Typography, Upload, message } from 'antd'
import type { FormInstance } from 'antd'
import { UploadOutlined, PlusOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { apiFetch, ApiError, jsonBody } from '../api/client'
import type { Account, DimensionType, DimensionValue, FixedAssetPreview, Ledger, LedgerRole, Member, OpeningBalance, Period, User } from '../api/types'
import { useAuth } from '../auth/AuthProvider'
import { decimalOrZero } from '../features/vouchers/money'
import { AccountsTab } from './AccountsTab'
import { LedgerBackupTab } from './LedgerBackupTab'

type OpeningFormLine = { accountId: string; periodId: string; currency: string; dimensionKey?: string; debitOriginal: string; creditOriginal: string; exchangeRate: string }
const decimalRule = { pattern: /^\d+(?:\.\d+)?$/, message: '请输入有效数字' }

export function SettingsPage() {
  const { ledgerId = '', '*': tab = 'periods' } = useParams(); const { session } = useAuth(); const client = useQueryClient(); const navigate = useNavigate(); const { modal } = AntApp.useApp(); const [messageApi, contextHolder] = message.useMessage()
  const periods = useQuery({ queryKey: ['periods', ledgerId], queryFn: () => apiFetch<Period[]>(`/ledgers/${ledgerId}/periods`, session!), enabled: Boolean(session && ledgerId) })
  const ledger = useQuery({ queryKey: ['ledger', ledgerId], queryFn: () => apiFetch<Ledger>(`/ledgers/${ledgerId}`, session!), enabled: Boolean(session && ledgerId) })
  const accounts = useQuery({ queryKey: ['accounts', ledgerId], queryFn: () => apiFetch<Account[]>(`/ledgers/${ledgerId}/accounts`, session!), enabled: Boolean(session && ledgerId) })
  const openings = useQuery({ queryKey: ['openings', ledgerId], queryFn: () => apiFetch<OpeningBalance[]>(`/ledgers/${ledgerId}/opening-balances`, session!), enabled: Boolean(session && ledgerId) })
  const members = useQuery({ queryKey: ['members', ledgerId], queryFn: () => apiFetch<Member[]>(`/ledgers/${ledgerId}/members`, session!), enabled: Boolean(session && ledgerId) })
  const ledgerRole = useQuery({ queryKey: ['ledger-role', ledgerId], queryFn: () => apiFetch<{ role: LedgerRole }>(`/ledgers/${ledgerId}/role`, session!), enabled: Boolean(session && ledgerId) })
  const dimensionTypes = useQuery({ queryKey: ['dimension-types', ledgerId], queryFn: () => apiFetch<DimensionType[]>(`/ledgers/${ledgerId}/dimension-types`, session!), enabled: Boolean(session && ledgerId) })
  const [selectedTypeId, setSelectedTypeId] = useState<string>()
  const [ledgerForm] = Form.useForm<{ name: string; description: string }>()
  useEffect(() => { if (ledger.data) ledgerForm.setFieldsValue({ name: ledger.data.name, description: ledger.data.description || '' }) }, [ledger.data, ledgerForm])
  const ledgerUpdate = useMutation({
    mutationFn: (value: { name: string; description: string }) => apiFetch<Ledger>(`/ledgers/${ledgerId}`, session!, { method: 'PATCH', body: jsonBody(value) }),
    onSuccess: (value) => { ledgerForm.setFieldsValue({ name: value.name, description: value.description || '' }); void client.invalidateQueries({ queryKey: ['ledger', ledgerId] }); messageApi.success('账套信息已保存') },
    onError: (error) => messageApi.error(error instanceof ApiError ? error.message : '账套信息保存失败'),
  })
  const dimensionValues = useQuery({ queryKey: ['dimension-values', ledgerId, selectedTypeId], queryFn: () => apiFetch<DimensionValue[]>(`/ledgers/${ledgerId}/dimension-types/${selectedTypeId}/values`, session!), enabled: Boolean(session && ledgerId && selectedTypeId) })
  const periodAction = useMutation({ mutationFn: ({ period, operation, reason }: { period: Period; operation: 'close' | 'reopen'; reason: string }) => apiFetch<Period>(`/ledgers/${ledgerId}/periods/${period.id}:${operation}`, session!, { method: 'POST', body: jsonBody({ reason }) }), onSuccess: () => void client.invalidateQueries({ queryKey: ['periods', ledgerId] }) })
  const openingSave = useMutation({ mutationFn: (lines: OpeningFormLine[]) => apiFetch<OpeningBalance[]>(`/ledgers/${ledgerId}/opening-balances`, session!, { method: 'PUT', body: jsonBody({ lines: lines.map((line) => ({ ...line, debitOriginal: String(line.debitOriginal), creditOriginal: String(line.creditOriginal), exchangeRate: String(line.exchangeRate) })) }) }), onSuccess: () => { messageApi.success('期初余额已保存'); void client.invalidateQueries({ queryKey: ['openings', ledgerId] }) }, onError: (error) => messageApi.error(error instanceof ApiError ? error.message : '期初余额保存失败') })
  const openingImport = useMutation({ mutationFn: (file: File) => { const body = new FormData(); body.append('file', file); return apiFetch<OpeningBalance[]>(`/ledgers/${ledgerId}/opening-balances:import-csv`, session!, { method: 'POST', body }) }, onSuccess: () => { messageApi.success('CSV 已导入'); void client.invalidateQueries({ queryKey: ['openings', ledgerId] }) }, onError: (error) => messageApi.error(error instanceof ApiError ? error.message : 'CSV 导入失败') })
  const confirmOpening = useMutation({ mutationFn: () => apiFetch<{ confirmedCount: number }>(`/ledgers/${ledgerId}/opening-balances:confirm`, session!, { method: 'POST' }), onSuccess: (value) => { messageApi.success(`已确认 ${value.confirmedCount} 行`); void client.invalidateQueries({ queryKey: ['openings', ledgerId] }) }, onError: (error) => messageApi.error(error instanceof ApiError ? error.message : '期初余额确认失败') })
  const [emailForm] = Form.useForm<{ email: string }>(); const [candidate, setCandidate] = useState<User | null>(null)
  const findCandidate = async ({ email }: { email: string }) => { try { const result = await apiFetch<User[]>(`/ledgers/${ledgerId}/member-candidates?email=${encodeURIComponent(email)}`, session!); setCandidate(result[0] || null); if (!result.length) messageApi.warning('没有找到已登录且有效的用户') } catch (error) { messageApi.error(error instanceof ApiError ? error.message : '成员查找失败') } }
  const addMember = async (role: LedgerRole) => { if (!candidate) return; try { await apiFetch<Member>(`/ledgers/${ledgerId}/members`, session!, { method: 'POST', body: jsonBody({ userId: candidate.id, role }) }); setCandidate(null); emailForm.resetFields(); messageApi.success('成员已添加'); void client.invalidateQueries({ queryKey: ['members', ledgerId] }) } catch (error) { messageApi.error(error instanceof ApiError ? error.message : '成员添加失败') } }
  const openReasonModal = (title: string, onConfirm: (reason: string) => void) => { let reason = ''; modal.confirm({ title, content: <Input autoFocus placeholder="原因必填" onChange={(event) => { reason = event.target.value }} />, onOk: () => { if (!reason.trim()) return Promise.reject(new Error('原因必填')); onConfirm(reason.trim()) } }) }
  const requestConfirmOpening = () => modal.confirm({ title: '确认期初余额？', content: '确认后将无法继续编辑或导入期初余额。', okText: '确认', okType: 'danger', cancelText: '取消', onOk: () => confirmOpening.mutateAsync() })
  const openClosePanel = async (period: Period) => {
    try {
      const preview = await apiFetch<FixedAssetPreview>(`/ledgers/${ledgerId}/fixed-asset-depreciation/preview?periodId=${period.id}`, session!)
      modal.confirm({ title: `期末处理 · ${period.periodCode}`, width: 560, content: <Space direction="vertical" style={{ width: '100%' }}><Typography.Text>应计折旧：{preview.totalAmount}，待处理资产：{preview.pendingCount}</Typography.Text>{preview.blockers.length ? <Alert type="warning" showIcon message="存在阻塞项" description={<ul>{preview.blockers.map((item) => <li key={item}>{item}</li>)}</ul>} /> : <Alert type="success" message="折旧状态正常，可以关账" />}</Space>, okText: preview.readyToClose ? '关账' : '生成折旧', onOk: async () => { if (!preview.readyToClose) { await apiFetch(`/ledgers/${ledgerId}/fixed-asset-depreciation:generate`, session!, { method: 'POST', body: jsonBody({ periodId: period.id }) }); messageApi.success('折旧凭证已生成，请再次执行关账'); return } await periodAction.mutateAsync({ period, operation: 'close', reason: '固定资产折旧已完成' }) } })
    } catch (error) { messageApi.error(error instanceof ApiError ? error.message : '期末处理检查失败') }
  }
  const changeTab = (key: string) => navigate(`/ledgers/${ledgerId}/settings/${key}`)
  return <>{contextHolder}<Space direction="vertical" size={16} style={{ width: '100%' }}><Typography.Title level={1}>账套设置</Typography.Title><Card title="账套基本信息"><Form form={ledgerForm} layout="vertical" onFinish={(value) => ledgerUpdate.mutate(value)}><Form.Item name="name" label="账套名称" rules={[{ required: true, message: '请输入账套名称' }]}><Input disabled={!['OWNER', 'EDITOR'].includes(ledgerRole.data?.role || '')} /></Form.Item><Form.Item name="description" label="公司主营业务" rules={[{ max: 2000, message: '主营业务描述不能超过 2000 个字符' }]}><Input.TextArea rows={4} maxLength={2000} showCount disabled={!['OWNER', 'EDITOR'].includes(ledgerRole.data?.role || '')} placeholder="例如：研发、生产和销售智能硬件及配套软件" /></Form.Item><Button type="primary" htmlType="submit" loading={ledgerUpdate.isPending} disabled={!['OWNER', 'EDITOR'].includes(ledgerRole.data?.role || '')}>保存</Button></Form></Card><Tabs activeKey={tab} onChange={changeTab} items={[
    { key: 'periods', label: '会计期间', children: <PeriodsTab periods={periods.data || []} onAction={(period, operation) => operation === 'close' ? void openClosePanel(period) : openReasonModal('反结账', (reason) => periodAction.mutate({ period, operation, reason }))} /> },
    { key: 'accounts', label: '科目', children: <AccountsTab ledgerId={ledgerId} session={session!} accounts={accounts.data || []} dimensionTypes={dimensionTypes.data || []} loading={accounts.isLoading} writable={['OWNER', 'EDITOR'].includes(ledgerRole.data?.role || '')} onChanged={() => void client.invalidateQueries({ queryKey: ['accounts', ledgerId] })} /> },
    { key: 'openings', label: '期初余额', children: <OpeningsTab rows={openings.data || []} accounts={accounts.data || []} periods={periods.data || []} onSave={(lines) => openingSave.mutate(lines)} saving={openingSave.isPending} onImport={(file) => openingImport.mutate(file)} importing={openingImport.isPending} onConfirm={requestConfirmOpening} confirming={confirmOpening.isPending} /> },
    { key: 'dimensions', label: '辅助核算', children: <DimensionsTab ledgerId={ledgerId} session={session!} types={dimensionTypes.data || []} values={dimensionValues.data || []} selectedTypeId={selectedTypeId} onSelect={setSelectedTypeId} onChanged={() => { void client.invalidateQueries({ queryKey: ['dimension-types', ledgerId] }); void client.invalidateQueries({ queryKey: ['dimension-values', ledgerId, selectedTypeId] }) }} /> },
    { key: 'members', label: '成员', children: <MembersTab rows={members.data || []} form={emailForm} candidate={candidate} onFind={findCandidate} onAdd={addMember} /> },
    { key: 'backup', label: '备份与恢复', children: <LedgerBackupTab ledgerId={ledgerId} session={session!} role={ledgerRole.data?.role} onRestored={(ledger) => navigate(`/ledgers/${ledger.id}/settings/backup`)} /> },
  ]} /></Space></>
}

function PeriodsTab({ periods, onAction }: { periods: Period[]; onAction: (period: Period, operation: 'close' | 'reopen') => void }) { return <Card><Table rowKey="id" dataSource={periods} columns={[{ title: '期间', dataIndex: 'periodCode' }, { title: '起止日期', render: (_: unknown, p: Period) => `${p.startDate} ~ ${p.endDate}` }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag color={value === 'OPEN' ? 'green' : 'default'}>{value}</Tag> }, { title: '操作', render: (_: unknown, p: Period) => p.status === 'OPEN' ? <Button onClick={() => onAction(p, 'close')}>关账</Button> : <Button onClick={() => onAction(p, 'reopen')}>反结账</Button> }]} /></Card> }

function OpeningsTab({ rows, accounts, periods, onSave, saving, onImport, importing, onConfirm, confirming }: { rows: OpeningBalance[]; accounts: Account[]; periods: Period[]; onSave: (lines: OpeningFormLine[]) => void; saving: boolean; onImport: (file: File) => void; importing: boolean; onConfirm: () => void; confirming: boolean }) {
  const [form] = Form.useForm<{ lines: OpeningFormLine[] }>()
  useEffect(() => { form.setFieldsValue({ lines: rows.map((row) => ({ accountId: row.accountId, periodId: row.periodId, currency: row.currency, dimensionKey: row.dimensionKey, debitOriginal: row.debitOriginal, creditOriginal: row.creditOriginal, exchangeRate: row.exchangeRate })) }) }, [rows, form])
  const watchedLines = Form.useWatch('lines', form) || []
  const totals = watchedLines.reduce((result, line) => ({ debit: result.debit.plus(decimalOrZero(line.debitOriginal).times(decimalOrZero(line.exchangeRate))), credit: result.credit.plus(decimalOrZero(line.creditOriginal).times(decimalOrZero(line.exchangeRate))) }), { debit: decimalOrZero(0), credit: decimalOrZero(0) })
  const confirmed = rows.some((row) => row.confirmed)
  return <Card extra={<Space><Upload disabled={confirmed} accept=".csv,text/csv" showUploadList={false} beforeUpload={(file) => { if (!file.name.toLowerCase().endsWith('.csv')) { message.error('只支持 CSV 文件'); return Upload.LIST_IGNORE } onImport(file); return false }}><Button icon={<UploadOutlined />} loading={importing} disabled={confirmed}>导入 CSV</Button></Upload><Button onClick={() => form.submit()} loading={saving} disabled={confirmed}>保存</Button><Button type="primary" onClick={onConfirm} loading={confirming} disabled={confirmed}>{confirmed ? '已确认' : '确认期初余额'}</Button></Space>}><Form form={form} disabled={confirmed} onFinish={(value) => onSave(value.lines)}><Form.List name="lines">{(fields, { add, remove }) => <><Table rowKey="key" dataSource={fields} pagination={false} scroll={{ x: 1000 }} columns={[{ title: '科目', render: (_, field) => <Form.Item name={[field.name, 'accountId']} rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={accounts.map((account) => ({ value: account.id, label: `${account.code} ${account.name}` }))} /></Form.Item> }, { title: '期间', render: (_, field) => <Form.Item name={[field.name, 'periodId']} rules={[{ required: true }]}><Select options={periods.map((period) => ({ value: period.id, label: period.periodCode }))} /></Form.Item> }, { title: '币种', render: (_, field) => <Form.Item name={[field.name, 'currency']} rules={[{ required: true, pattern: /^[A-Z]{3}$/ }]}><Input maxLength={3} /></Form.Item> }, { title: '维度键', render: (_, field) => <Form.Item name={[field.name, 'dimensionKey']}><Input /></Form.Item> }, { title: '借方', render: (_, field) => <Form.Item name={[field.name, 'debitOriginal']} rules={[{ required: true }, decimalRule]}><Input inputMode="decimal" /></Form.Item> }, { title: '贷方', render: (_, field) => <Form.Item name={[field.name, 'creditOriginal']} rules={[{ required: true }, decimalRule]}><Input inputMode="decimal" /></Form.Item> }, { title: '汇率', render: (_, field) => <Form.Item name={[field.name, 'exchangeRate']} rules={[{ required: true }, decimalRule]}><Input inputMode="decimal" /></Form.Item> }, { title: '操作', render: (_, field) => <Button type="link" danger onClick={() => remove(field.name)}>删除</Button> }]} /><Button icon={<PlusOutlined />} onClick={() => add({ currency: 'CNY', debitOriginal: '0', creditOriginal: '0', exchangeRate: '1' })}>添加期初行</Button></> }</Form.List></Form><Typography.Paragraph>借方合计：{totals.debit.toFixed(2)} / 贷方合计：{totals.credit.toFixed(2)}</Typography.Paragraph></Card>
}

function DimensionsTab({ ledgerId, session, types, values, selectedTypeId, onSelect, onChanged }: { ledgerId: string; session: NonNullable<ReturnType<typeof useAuth>['session']>; types: DimensionType[]; values: DimensionValue[]; selectedTypeId?: string; onSelect: (id: string) => void; onChanged: () => void }) {
  const [typeForm] = Form.useForm<{ code: string; name: string; required?: boolean }>(); const [valueForm] = Form.useForm<{ code: string; name: string }>()
  const createType = async (form: { code: string; name: string; required?: boolean }) => { await apiFetch<DimensionType>(`/ledgers/${ledgerId}/dimension-types`, session, { method: 'POST', body: jsonBody(form) }); typeForm.resetFields(); onChanged() }
  const createValue = async (form: { code: string; name: string }) => { if (!selectedTypeId) return; await apiFetch<DimensionValue>(`/ledgers/${ledgerId}/dimension-types/${selectedTypeId}/values`, session, { method: 'POST', body: jsonBody(form) }); valueForm.resetFields(); onChanged() }
  return <Space direction="vertical" style={{ width: '100%' }}><Card title="新增辅助核算类型"><Form form={typeForm} layout="inline" onFinish={(value) => void createType(value as { code: string; name: string; required?: boolean })}><Form.Item name="code" rules={[{ required: true }]}><Input placeholder="PROJECT" /></Form.Item><Form.Item name="name" rules={[{ required: true }]}><Input placeholder="项目" /></Form.Item><Form.Item name="required" valuePropName="checked"><input type="checkbox" aria-label="必填" /></Form.Item><Button htmlType="submit" type="primary">新增类型</Button></Form></Card><Card title="类型和值"><Space align="start" style={{ width: '100%' }}><Table rowKey="id" size="small" dataSource={types} pagination={false} style={{ flex: 1 }} columns={[{ title: '编码', dataIndex: 'code' }, { title: '名称', dataIndex: 'name' }, { title: '必填', dataIndex: 'required', render: (value: boolean) => value ? '是' : '否' }, { title: '操作', render: (_: unknown, row: DimensionType) => <Button type="link" onClick={() => onSelect(row.id)}>查看值</Button> }]} /><Card size="small" title={types.find((type) => type.id === selectedTypeId)?.name || '请选择类型'} style={{ minWidth: 320 }}><Form form={valueForm} layout="inline" onFinish={(value) => void createValue(value as { code: string; name: string })}><Form.Item name="code" rules={[{ required: true }]}><Input placeholder="CODE" /></Form.Item><Form.Item name="name" rules={[{ required: true }]}><Input placeholder="名称" /></Form.Item><Button htmlType="submit" disabled={!selectedTypeId}>新增值</Button></Form><Table rowKey="id" size="small" dataSource={values} pagination={false} columns={[{ title: '编码', dataIndex: 'code' }, { title: '名称', dataIndex: 'name' }]} /></Card></Space></Card></Space>
}

function MembersTab({ rows, form, candidate, onFind, onAdd }: { rows: Member[]; form: FormInstance<{ email: string }>; candidate: User | null; onFind: (value: { email: string }) => void; onAdd: (role: LedgerRole) => Promise<void> }) { const [role, setRole] = useState<LedgerRole>('VIEWER'); const [adding, setAdding] = useState(false); const add = async () => { setAdding(true); try { await onAdd(role) } finally { setAdding(false) } }; return <Space direction="vertical" style={{ width: '100%' }}><Card title="按邮箱添加已存在用户"><Form form={form} layout="inline" onFinish={(value) => void onFind(value as { email: string })}><Form.Item name="email" rules={[{ required: true, type: 'email' }]}><Input placeholder="user@example.com" /></Form.Item><Button htmlType="submit">精确查找</Button></Form>{candidate && <Space style={{ marginTop: 12 }}><Typography.Text>{candidate.displayName || candidate.email}</Typography.Text><Select value={role} options={['EDITOR', 'REVIEWER', 'VIEWER'].map((value) => ({ value, label: value }))} onChange={(value) => setRole(value as LedgerRole)} /><Button type="primary" loading={adding} onClick={() => void add()}>添加成员</Button></Space>}</Card><Card><Table rowKey="userId" dataSource={rows} columns={[{ title: '用户', render: (_: unknown, row: Member) => row.displayName || row.email || row.userId }, { title: '邮箱', dataIndex: 'email' }, { title: '角色', dataIndex: 'role' }, { title: '状态', dataIndex: 'status' }]} /></Card></Space> }
