import Decimal from 'decimal.js'
import { Alert, App as AntApp, Button, Card, Col, DatePicker, Empty, Form, Input, Modal, Row, Select, Space, Table, Tag, Typography } from 'antd'
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import dayjs, { type Dayjs } from 'dayjs'
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { apiFetch, createIdempotencyKey, jsonBody, ApiError } from '../api/client'
import type { Account, Period, Voucher, VoucherRevision } from '../api/types'
import { useAuth } from '../auth/AuthProvider'

type VoucherForm = { periodId: string; voucherDate: Dayjs; voucherType: string; voucherNumber: string; summary?: string; lines: Array<{ accountId: string; side: 'DEBIT' | 'CREDIT'; currency: string; originalAmount: string; exchangeRate: string; summary?: string }> }
const money = (value: unknown) => new Decimal(String(value || '0'))
const emptyLines: VoucherForm['lines'] = []

export function VoucherListPage() {
  const { ledgerId = '' } = useParams(); const { session } = useAuth(); const navigate = useNavigate(); const [search, setSearch] = useSearchParams()
  const limit = Number(search.get('limit') || 20); const offset = Number(search.get('offset') || 0)
  const query = useQuery({ queryKey: ['vouchers', ledgerId, limit, offset], queryFn: () => apiFetch<Voucher[]>(`/ledgers/${ledgerId}/vouchers?limit=${limit}&offset=${offset}`, session!), enabled: Boolean(session && ledgerId) })
  return <Space direction="vertical" size={16} style={{ width: '100%' }}>
    <div className="page-heading"><div><Typography.Title level={1}>凭证工作台</Typography.Title><Typography.Text type="secondary">录入、校验并推进凭证状态。</Typography.Text></div><Button type="primary" icon={<PlusOutlined />} onClick={() => navigate(`/ledgers/${ledgerId}/vouchers/new`)}>新建凭证</Button></div>
    {query.isError && <Alert type="error" showIcon message="凭证列表读取失败" action={<Button icon={<ReloadOutlined />} onClick={() => void query.refetch()}>重试</Button>} />}
    <Card><Table rowKey="id" loading={query.isLoading} dataSource={query.data || []} locale={{ emptyText: <Empty description="暂无凭证" /> }} pagination={{ current: Math.floor(offset / limit) + 1, pageSize: limit, total: (offset + (query.data?.length || 0)) + (query.data?.length === limit ? 1 : 0), showSizeChanger: false, onChange: (page) => setSearch({ limit: String(limit), offset: String((page - 1) * limit) }) }} columns={[
      { title: '凭证号', dataIndex: 'voucherNumber', render: (value: string, row: Voucher) => <Link to={`/ledgers/${ledgerId}/vouchers/${row.id}`}>{row.voucherType}-{value}</Link> },
      { title: '日期', dataIndex: 'voucherDate' }, { title: '摘要', dataIndex: 'summary' }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag>{value}</Tag> }, { title: '版本', dataIndex: 'version' },
    ]} /></Card>
  </Space>
}

export function VoucherEditorPage() {
  const { ledgerId = '', voucherId } = useParams(); const { session } = useAuth(); const client = useQueryClient(); const navigate = useNavigate(); const { modal } = AntApp.useApp(); const [form] = Form.useForm<VoucherForm>(); const [commentAction, setCommentAction] = useState<'approve' | 'reject' | 'unpost' | null>(null)
  const accounts = useQuery({ queryKey: ['accounts', ledgerId], queryFn: () => apiFetch<Account[]>(`/ledgers/${ledgerId}/accounts`, session!), enabled: Boolean(session && ledgerId) })
  const periods = useQuery({ queryKey: ['periods', ledgerId], queryFn: () => apiFetch<Period[]>(`/ledgers/${ledgerId}/periods`, session!), enabled: Boolean(session && ledgerId) })
  const voucher = useQuery({ queryKey: ['voucher', ledgerId, voucherId], queryFn: () => apiFetch<Voucher>(`/ledgers/${ledgerId}/vouchers/${voucherId}`, session!), enabled: Boolean(session && ledgerId && voucherId && voucherId !== 'new') })
  const revisions = useQuery({ queryKey: ['voucher-revisions', ledgerId, voucherId], queryFn: () => apiFetch<VoucherRevision[]>(`/ledgers/${ledgerId}/vouchers/${voucherId}/revisions`, session!), enabled: Boolean(session && ledgerId && voucherId && voucherId !== 'new') })
  const watchedLines = Form.useWatch('lines', form)
  const lines = watchedLines ?? emptyLines
  const totals = useMemo(() => lines.reduce((sum, line) => { const amount = money(line.originalAmount).times(money(line.exchangeRate)); return { debit: line.side === 'DEBIT' ? sum.debit.plus(amount) : sum.debit, credit: line.side === 'CREDIT' ? sum.credit.plus(amount) : sum.credit } }, { debit: new Decimal(0), credit: new Decimal(0) }), [lines])
  const save = useMutation({ mutationFn: async (value: VoucherForm) => { const body = { ...(voucherId && voucherId !== 'new' ? { expectedVersion: voucher.data?.version } : {}), periodId: value.periodId, voucherDate: value.voucherDate.format('YYYY-MM-DD'), voucherType: value.voucherType, voucherNumber: value.voucherNumber, summary: value.summary, lines: value.lines.map((line) => ({ ...line, originalAmount: String(line.originalAmount), exchangeRate: String(line.exchangeRate) })) }; return voucherId && voucherId !== 'new' ? apiFetch<Voucher>(`/ledgers/${ledgerId}/vouchers/${voucherId}`, session!, { method: 'PUT', body: jsonBody(body) }) : apiFetch<Voucher>(`/ledgers/${ledgerId}/vouchers`, session!, { method: 'POST', headers: { 'Idempotency-Key': createIdempotencyKey() }, body: jsonBody(body) }) }, onSuccess: (value) => { void client.invalidateQueries({ queryKey: ['vouchers', ledgerId] }); navigate(`/ledgers/${ledgerId}/vouchers/${value.id}`) } })
  const action = async (name: string, body?: unknown) => { if (!voucherId || voucherId === 'new') return; try { await apiFetch<Voucher>(`/ledgers/${ledgerId}/vouchers/${voucherId}:${name}`, session!, { method: 'POST', body: body ? jsonBody(body) : undefined }); await voucher.refetch(); void client.invalidateQueries({ queryKey: ['vouchers', ledgerId] }) } catch (error) { if (error instanceof ApiError && error.status === 409) modal.error({ title: '凭证已被其他人修改', content: '请刷新后确认是否放弃本地修改。' }) } }
  const restoreRevision = async (revision: number) => { if (!voucherId || voucherId === 'new') return; await apiFetch<Voucher>(`/ledgers/${ledgerId}/vouchers/${voucherId}/revisions/${revision}:restore`, session!, { method: 'POST' }); await voucher.refetch(); void revisions.refetch(); void client.invalidateQueries({ queryKey: ['vouchers', ledgerId] }) }
  const initial = voucher.data ? { ...voucher.data, voucherDate: dayjs(voucher.data.voucherDate), lines: voucher.data.lines.map((line) => ({ ...line, originalAmount: line.originalAmount, exchangeRate: line.exchangeRate })) } : { voucherDate: dayjs(), voucherType: '记', lines: [{ side: 'DEBIT', currency: 'CNY', originalAmount: '0', exchangeRate: '1' }] }
  useEffect(() => { if (voucher.data) form.setFieldsValue({ ...voucher.data, voucherDate: dayjs(voucher.data.voucherDate), lines: voucher.data.lines.map((line) => ({ ...line, originalAmount: line.originalAmount, exchangeRate: line.exchangeRate })) } as VoucherForm) }, [voucher.data, form])
  if (voucher.isError) return <Alert type="error" message="凭证读取失败" />
  return <Space direction="vertical" size={16} style={{ width: '100%' }}>
    <div className="page-heading"><div><Typography.Title level={1}>{voucherId === 'new' ? '新建凭证' : '凭证详情'}</Typography.Title><Typography.Text type="secondary">{voucher.data ? `版本 ${voucher.data.version} · ${voucher.data.status}` : '保存后可继续校验和记账'}</Typography.Text></div><Button onClick={() => navigate(`/ledgers/${ledgerId}/vouchers`)}>返回列表</Button></div>
    <Card><Form form={form} layout="vertical" initialValues={initial} onFinish={(value) => save.mutate(value as VoucherForm)}>
      <Row gutter={16}><Col xs={24} md={8}><Form.Item name="periodId" label="会计期间" rules={[{ required: true }]}><Select options={(periods.data || []).map((period) => ({ value: period.id, label: `${period.periodCode} (${period.status})` }))} /></Form.Item></Col><Col xs={24} md={8}><Form.Item name="voucherDate" label="凭证日期" rules={[{ required: true }]}><DatePicker style={{ width: '100%' }} /></Form.Item></Col><Col xs={24} md={8}><Form.Item name="voucherType" label="凭证字" rules={[{ required: true }]}><Input /></Form.Item></Col></Row>
      <Row gutter={16}><Col xs={24} md={8}><Form.Item name="voucherNumber" label="凭证号" rules={[{ required: true }]}><Input /></Form.Item></Col><Col xs={24} md={16}><Form.Item name="summary" label="摘要"><Input /></Form.Item></Col></Row>
      <Form.List name="lines">{(fields, { add, remove }) => <><Table pagination={false} rowKey="key" dataSource={fields} columns={[{ title: '科目', render: (_, field) => <Form.Item name={[field.name, 'accountId']} rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={(accounts.data || []).map((account) => ({ value: account.id, label: `${account.code} ${account.name}` }))} /></Form.Item> }, { title: '方向', render: (_, field) => <Form.Item name={[field.name, 'side']} rules={[{ required: true }]}><Select options={[{ value: 'DEBIT', label: '借' }, { value: 'CREDIT', label: '贷' }]} /></Form.Item> }, { title: '币种', render: (_, field) => <Form.Item name={[field.name, 'currency']} rules={[{ required: true }]}><Input maxLength={3} /></Form.Item> }, { title: '原币金额', render: (_, field) => <Form.Item name={[field.name, 'originalAmount']} rules={[{ required: true }]}><Input /></Form.Item> }, { title: '汇率', render: (_, field) => <Form.Item name={[field.name, 'exchangeRate']} rules={[{ required: true }]}><Input /></Form.Item> }, { title: '操作', render: (_, field) => <Button type="link" danger onClick={() => remove(field.name)}>删除</Button> }]} /><Button style={{ marginTop: 12 }} onClick={() => add({ side: 'DEBIT', currency: 'CNY', originalAmount: '0', exchangeRate: '1' })}>添加分录</Button></> }</Form.List>
      <Typography.Paragraph>借方合计：{totals.debit.toFixed(2)} / 贷方合计：{totals.credit.toFixed(2)}</Typography.Paragraph>
      <Space><Button type="primary" htmlType="submit" loading={save.isPending}>保存草稿</Button>{voucherId && voucherId !== 'new' && <><Button onClick={() => void action('validate')}>校验</Button><Button onClick={() => void action('submit')}>提交</Button><Button onClick={() => setCommentAction('approve')}>审批</Button><Button onClick={() => setCommentAction('reject')}>退回</Button><Button type="primary" onClick={() => void action('post')}>记账</Button><Button onClick={() => setCommentAction('unpost')}>反记账</Button><Button danger onClick={() => void action('reverse')}>冲销</Button></>}</Space>
    </Form></Card>
    {voucherId && voucherId !== 'new' && <Card title="历史版本" extra={<Typography.Text type="secondary">恢复后会生成新的版本</Typography.Text>}><Table rowKey="revision" loading={revisions.isLoading} dataSource={revisions.data || []} pagination={false} scroll={{ x: 800 }} columns={[{ title: '修订号', dataIndex: 'revision' }, { title: '操作', dataIndex: 'action' }, { title: '原因', dataIndex: 'reason' }, { title: '时间', dataIndex: 'createdAt', render: (value: string) => new Date(value).toLocaleString('zh-CN') }, { title: '操作', render: (_: unknown, row: VoucherRevision) => <Button onClick={() => modal.confirm({ title: `恢复修订 ${row.revision}？`, content: '当前内容会保留在新的历史版本中。', okText: '恢复', cancelText: '取消', onOk: () => restoreRevision(row.revision) })}>恢复</Button> }]} /></Card>}
    <Modal open={Boolean(commentAction)} title="填写原因" okText="确认" cancelText="取消" onCancel={() => setCommentAction(null)} onOk={() => { const value = (document.querySelector('#voucher-action-comment') as HTMLInputElement)?.value; if (value) { void action(commentAction === 'unpost' ? 'unpost' : commentAction || 'approve', commentAction === 'unpost' ? { reason: value } : { comment: value }); setCommentAction(null) } }}><Input id="voucher-action-comment" placeholder="原因不能为空" /></Modal>
  </Space>
}
