create table account_period_balance (
    ledger_id uuid not null,
    period_id uuid not null,
    account_id uuid not null,
    opening_debit_base numeric(19, 2) not null default 0,
    opening_credit_base numeric(19, 2) not null default 0,
    period_debit_base numeric(19, 2) not null default 0,
    period_credit_base numeric(19, 2) not null default 0,
    finalized_at timestamptz,
    version bigint not null default 0,
    updated_at timestamptz not null default now(),
    primary key (ledger_id, period_id, account_id),
    constraint fk_account_period_balance_period foreign key (ledger_id, period_id)
        references accounting_period (ledger_id, id),
    constraint fk_account_period_balance_account foreign key (ledger_id, account_id)
        references ledger_account (ledger_id, id),
    constraint ck_account_period_balance_amounts check (
        opening_debit_base >= 0 and opening_credit_base >= 0
        and period_debit_base >= 0 and period_credit_base >= 0)
);

create index ix_account_period_balance_period
    on account_period_balance (ledger_id, period_id, account_id);

create table balance_projection_event (
    id bigint generated by default as identity primary key,
    ledger_id uuid not null references ledger (id),
    period_id uuid not null,
    aggregate_type varchar(32) not null,
    aggregate_id uuid not null,
    aggregate_version bigint not null,
    event_type varchar(32) not null,
    created_at timestamptz not null default now(),
    constraint fk_balance_projection_event_period foreign key (ledger_id, period_id)
        references accounting_period (ledger_id, id),
    constraint uk_balance_projection_event_version
        unique (aggregate_type, aggregate_id, aggregate_version, event_type),
    constraint ck_balance_projection_event_aggregate_type
        check (aggregate_type in ('VOUCHER', 'OPENING_BALANCE')),
    constraint ck_balance_projection_event_type
        check (event_type in ('POST', 'UNPOST', 'OPENING_CONFIRM'))
);

create index ix_balance_projection_event_period_id
    on balance_projection_event (ledger_id, period_id, id);

create table balance_projection_event_line (
    event_id bigint not null references balance_projection_event (id) on delete cascade,
    ledger_id uuid not null,
    account_id uuid not null,
    opening_debit_delta numeric(19, 2) not null default 0,
    opening_credit_delta numeric(19, 2) not null default 0,
    period_debit_delta numeric(19, 2) not null default 0,
    period_credit_delta numeric(19, 2) not null default 0,
    primary key (event_id, account_id),
    constraint fk_balance_projection_event_line_account foreign key (ledger_id, account_id)
        references ledger_account (ledger_id, id)
);

create index ix_balance_projection_event_line_event
    on balance_projection_event_line (event_id, account_id);

create table balance_projection_state (
    ledger_id uuid not null,
    period_id uuid not null,
    last_enqueued_event_id bigint,
    last_applied_event_id bigint,
    last_enqueued_at timestamptz,
    projected_at timestamptz,
    status varchar(32) not null default 'READY',
    last_error_code varchar(64),
    last_error_message varchar(1000),
    updated_at timestamptz not null default now(),
    primary key (ledger_id, period_id),
    constraint fk_balance_projection_state_period foreign key (ledger_id, period_id)
        references accounting_period (ledger_id, id),
    constraint ck_balance_projection_state_status
        check (status in ('READY', 'REBUILDING', 'FAILED'))
);

create index ix_balance_projection_state_pending
    on balance_projection_state (status, last_applied_event_id, last_enqueued_event_id);

create table balance_rebuild_job (
    id uuid primary key,
    ledger_id uuid not null references ledger (id),
    period_from varchar(7),
    period_to varchar(7),
    status varchar(32) not null default 'QUEUED',
    reason varchar(1000) not null,
    requested_by uuid not null references app_user (id),
    processed_periods integer not null default 0,
    total_periods integer not null default 0,
    difference_count integer not null default 0,
    last_error_code varchar(64),
    last_error_message varchar(1000),
    created_at timestamptz not null default now(),
    started_at timestamptz,
    completed_at timestamptz,
    constraint ck_balance_rebuild_job_status
        check (status in ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    constraint ck_balance_rebuild_job_period_range
        check ((period_from is null and period_to is null) or
               (period_from is not null and period_to is not null and period_from <= period_to))
);

create index ix_balance_rebuild_job_ledger_created
    on balance_rebuild_job (ledger_id, created_at desc);
