create table balance_rebuild_audit (
    id bigint generated by default as identity primary key,
    ledger_id uuid not null references ledger (id),
    job_id uuid not null references balance_rebuild_job (id),
    actor_id uuid not null references app_user (id),
    action varchar(32) not null,
    reason varchar(1000) not null,
    created_at timestamptz not null default now(),
    constraint ck_balance_rebuild_audit_action check (action in ('REQUEST'))
);

create index ix_balance_rebuild_audit_job on balance_rebuild_audit (ledger_id, job_id, created_at);
